# Generated by Django 3.2.8 on 2022-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificaciones',
            name='img_nuestros_servicios_fondo',
            field=models.ImageField(null=True, upload_to='our_service'),
        ),
    ]
